WIDTH = 930
HEIGHT = 630
BORDER_WIDTH = 40
CENTER_BAR_WIDTH = 50
TRIANGLE_HEIGHT = 220
CHECKER_RADIUS = 24
DICE_SIZE = 50
DONE_BUTTON_SIZE = 40

PLAY_AREA_START_X = BORDER_WIDTH
PLAY_AREA_END_X = WIDTH - BORDER_WIDTH
PLAY_AREA_START_Y = BORDER_WIDTH
PLAY_AREA_END_Y = HEIGHT - BORDER_WIDTH
LEFT_BOARD_END_X = WIDTH / 2 - CENTER_BAR_WIDTH / 2
RIGHT_BOARD_START_X = WIDTH / 2 + CENTER_BAR_WIDTH / 2

BOARD_COLOR = "#F4BB92"
BORDER_COLOR = "#8B4513"
POINT_COLOR_BLACK = "#171717"
POINT_COLOR_RED = "#A52A2A"
COLOR_PLAYER0 = "#FFFFFF"
COLOR_PLAYER1 = "#1E1E1E"
HIGHLIGHT_COLOR = "#24A524"
HINT_HIGHLIGHT_COLOR = "#ffea00"